
import Head from 'next/head'
import Auth from '@/pages/auth/[auth]'

export default function Home(props) {
  // cosole.log("props",props)
  return (
    <>
      <Head>
        <title>{process.env.SITE_TITLE} - {props.pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta httpEquiv="cache-control" content="max-age=0" />
        <meta httpEquiv="cache-control" content="no-cache" />
        <meta httpEquiv="expires" content="0" />
        <meta httpEquiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
        <meta httpEquiv="pragma" content="no-cache" />
        <link rel="shortcut icon" href="../assets/images/favicsdson .png" />
      </Head>
      <Auth/>
      
    </>
  )
}



